micronaut:
  application:
    name: datoid-indexer
  server:
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"

datoid:
  url: https://datoid.cz
  poll:
    interval: 60s

elasticsearch.httpHosts: 'http://localhost:9200'
